version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080" # interface web
      - "50000:50000" # agent Jenkins (utile pour future extension)
    volumes:
      - jenkins_home:/var/jenkins_home # persistance des données
      - /var/run/docker.sock:/var/run/docker.sock # pour utiliser Docker à l'intérieur de Jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
