global:
  scrape_interval: 15s # Prometheus interroge toutes les 15 secondes

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus" # endpoint expos√© par Spring Boot
    static_configs:
      - targets: ["host.docker.internal:8081"]
